#
# Copyright 2025 William Swartzendruber
#
# To the extent possible under law, the person who associated CC0 with this file has waived all
# copyright and related or neighboring rights to this file.
#
# You should have received a copy of the CC0 legalcode along with this work. If not, see
# <http://creativecommons.org/publicdomain/zero/1.0/>.
#
# SPDX-License-Identifier: CC0-1.0
#

name: 'Create Release'
on:
  push:
    tags:
      - 'release/*'
env:
  CONFIGURATION: 'Release'
jobs:
  build:
    name: 'Build & Publish'
    runs-on: ubuntu-24.04
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
    - name: 'Extract Version'
      run: echo "VERSION=$(echo "$GITHUB_REF_NAME" | sed -e 's/^release\///')" >> $GITHUB_ENV
    - name: '.NET: Setup'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: 'NuGet: Setup'
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: '6.x'
        nuget-api-key: "${{ secrets.NUGET_API_KEY_GITHUB }}"
    - name: '.NET: Build'
      run: dotnet build --configuration "$CONFIGURATION" --property:Version="$VERSION"
    - name: '.NET: Test'
      run: dotnet test --configuration "$CONFIGURATION" --property:Version="$VERSION"
    - name: '.NET: Pack'
      run: dotnet pack --configuration "$CONFIGURATION" --property:Version="$VERSION"
    - name: 'NuGet: Push'
      run: nuget push **/*.nupkg -Source "https://api.nuget.org/v3/index.json" -ApiKey "${{ secrets.NUGET_API_KEY }}"
