name: 'Create Release'
on:
  push:
    tags:
      - 'release/*'
env:
  CONFIGURATION: 'Release'
jobs:
  build:
    name: 'Build & Publish'
    runs-on: ubuntu-22.04
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
    - name: 'Extract Version'
      run: echo "VERSION=$(echo "$GITHUB_REF_NAME" | sed -e 's/^release\///')" >> $GITHUB_ENV
    - name: '.NET: Setup'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: 'NuGet: Setup'
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: '6.x'
        nuget-api-key: "${{ secrets.NUGET_API_KEY_GITHUB }}"
    - name: '.NET: Build'
      run: dotnet build --configuration "$CONFIGURATION" --property:Version="$VERSION"
    - name: '.NET: Test'
      run: dotnet test --configuration "$CONFIGURATION" --property:Version="$VERSION"
    - name: '.NET: Pack'
      run: dotnet pack --configuration "$CONFIGURATION" --property:Version="$VERSION"
    - name: 'NuGet: Push'
      run: nuget push **/*.nupkg -Source "https://api.nuget.org/v3/index.json" -ApiKey "${{ secrets.NUGET_API_KEY }}"
